---
title: "Moduke 8"
author: "biRds"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(rgbif)
library(dplyr)
library(tidyverse)
library(MuMIn)
library(rnoaa)
library(data.table)
library(ggmap)
library(usmap)
library(lme4)
library(car)
```

```{r, "Ebird Set up" , include=FALSE}
species <- c("Setophaga dominica","Vireo griseus","Vireo flavifrons","Vermivora chrysoptera","Setophaga virens")

y <- paste0("1990",",","2019")
m <- paste0("3",",","6")

dat.l <-list()

for(s in species){
  n.obs <-  occ_data(scientificName = s, year = y, month = m, limit = 0, country = "US", basisOfRecord = "HUMAN_OBSERVATION", stateProvince="Massachusetts")$meta$count 

print(n.obs)

dat.l[[paste0(s)]] <- occ_data(scientificName = s, year = y, month = m, 
                               limit = n.obs, country = "US",
                               basisOfRecord = "HUMAN_OBSERVATION",
                               stateProvince = "Massachusetts")[[2]]

}

dat <- rbindlist(dat.l,fill=T)

dat%>%
  group_by(year, species)%>%
  summarise(count=sum(individualCount,na.rm = T))%>%
  ggplot(aes(x=year,y=count,col=species))+geom_point()

```

```{r, "Weather Set up" , include=FALSE}

options(noaakey = "MNNiOTQiqymUOFxyhavrXdSobVKuKJyr")

sts <- c(
  "GHCND:USW00013894", #Mobile
  "GHCND:USW00013881", #Charlotte
  "GHCND:USW00014739" #Boston
)

#making one table w/ info about location of the stations
sta.d <- bind_rows( #bind the rows
  lapply(sts,function(x) ncdc_stations(stationid = x)$data ) #use lapply to run through stations
  )%>%
  mutate(usmap_transform(.,input_names = c("longitude","latitude"),output_names = c("longitude.1", "latitude.1")))%>% #join transformation of lat/long for projection with usmap
  mutate(name=str_sub(name, -5,-4))%>%#simplify the name column, grab just the state
  mutate(migr.day=c(10,5,0))%>% #so we can look at wind speed 0, 5 or 10 days before arrive in boston
  separate(id,into = c("station.type","id"))%>%#need to cut station type out from station id number
        print()

#plotting the image of where the stations are
plot_usmap(
  include = c(.northeast_region,.south_region,.east_north_central)
)+geom_point(data=sta.d,aes(x=longitude.1,y=latitude.1,col=name),size=5)+geom_label(data=sta.d,aes(x=longitude.1,y=latitude.1,col=name,label=name),size=5,nudge_x = 1e6*0.25)+theme(legend.position = "none")

#getting  weather info and print table 
weather.d <- meteo_pull_monitors(sta.d$id,date_min = "2000-01-01")
head(weather.d)
```

```{r, "EBird Data Prep" , include=FALSE}
mc<- dat%>%
  filter(species=="Setophaga dominica")%>%
  group_by(year)%>%
  mutate(date=as.Date(paste0(year,"-",month,"-",day)),
         j.day=julian(date,origin=as.Date(paste0(unique(year),"-01-01")))
  )%>%
  group_by(species,year,j.day,date)%>%
  summarise(day.tot=sum(individualCount,na.rm=T))%>%
  group_by(species,year)%>%
  mutate(prop=cumsum(day.tot/sum(day.tot,na.rm = T)))%>%
  filter(year>1999)

mc%>%
  ggplot(aes(j.day,prop))+geom_point()+facet_wrap(year~.)

mc.pred <- mc%>%
  group_by(year)%>%
 summarize(
   pred=predict(nls(prop~SSlogis(j.day,Asym, xmid, scal)),newdata=data.frame(j.day=min(j.day):max(j.day))),#predict the logistic curve for each species
   j.day=min(j.day):max(j.day),
  )%>%
  left_join(mc%>%dplyr::select(j.day,date))
mc%>%
  ggplot(aes(j.day,prop))+geom_point(aes=0.3)+geom_line(data=mc.pred,aes(x=j.day,y=pred),col="blue",size=2)+facet_wrap(year~.)

````
